spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: employee-api
          uri: http://localhost:9000
          predicates:
            - Path=/employee/**
        - id: payroll-api
          uri: http://localhost:9010
          predicates:
            - Path=/payroll/**
server:
  port: 8085
